# Generated by Django 4.2.7 on 2023-11-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, default='Bangalore', max_length=20)),
                ('Activity_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('Mother_tongue', models.CharField(blank=True, max_length=20, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('Income', models.IntegerField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Religion', models.CharField(blank=True, max_length=20, null=True)),
                ('Drink', models.IntegerField(blank=True, choices=[(1, 'Drink'), (2, 'No-Drink')], null=True)),
                ('Smoke', models.IntegerField(blank=True, choices=[(1, 'Smoke'), (2, 'No-Smoke')], null=True)),
                ('Diet', models.IntegerField(blank=True, choices=[(1, 'Veg'), (2, 'Non-Veg')], null=True)),
                ('Highest_Education', models.CharField(blank=True, max_length=20, null=True)),
                ('Prev_Marital_Status', models.IntegerField(blank=True, choices=[(1, 'Married'), (2, 'Divorced'), (3, 'Unmarried')], null=True)),
                ('About_Me', models.CharField(blank=True, max_length=200, null=True)),
                ('Matched', models.IntegerField(blank=True, choices=[(1, 'Matched'), (2, 'Unmatched')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPref',
            fields=[
                ('Cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Age_min', models.IntegerField()),
                ('Age_max', models.IntegerField()),
                ('Religion', models.CharField(max_length=20)),
                ('Diet', models.IntegerField(choices=[(1, 'Veg'), (2, 'Non-Veg')])),
                ('Income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('Cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Pic1', models.ImageField(upload_to='pics')),
                ('Pic2', models.ImageField(upload_to='pics')),
                ('Pic3', models.ImageField(upload_to='pics')),
                ('Pic4', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=200)),
                ('Rating', models.IntegerField()),
                ('Cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
