# Generated by Django 4.2.7 on 2023-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='Pic1',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='Pic2',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='Pic3',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='Pic4',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
